export const UPDATE_DATA_TYPE = {
    NAME: 'UPDATE_DATA_TYPE.NAME',
    TIME_ZONE: 'UPDATE_DATA_TYPE.TIME_ZONE',
    PHONE: 'UPDATE_DATA_TYPE.PHONE'
}

export const UPDATE_DATA_FAILED = {
    PHONE_NUMBER_IN_USED: 'PHONE_NUMBER_IN_USED'
}