// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/riotjs/riotjs.d.ts
interface JQueryStatic {
    riot: string;
    observable(el:any):any;
    route(to:any):void;
}
