export const COMMONS = {
    TOGGLE_LOADING: 'COMMONS.TOGGLE_LOADING',
    SET_ACTIVE_TAB: 'COMMONS.SET_ACTIVE_TAB'
};

export const USERS = {
    LOGIN: 'USERS.LOGIN',
    LOGIN_SUCCESS: 'USERS.LOGIN_SUCCESS',
    LOGIN_FAILED: 'USERS.LOGIN_FAILED',
    LOGOUT: 'USERS.LOGOUT',
    SSO_LOGIN_SUCCESS: 'USERS.SSO_LOGIN_SUCCESS',
    SSO_LOGIN_FAILED: 'USERS.SSO_LOGIN_FAILED',
    GET_PROFILE_SUCCESS: 'USERS.GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED: 'USERS.GET_PROFILE_FAILED',
    REMEMBER_ME: 'USERS.REMEMBER_ME',
    SAVE_ACCESS_TOKEN: 'USERS.SAVE_ACCESS_TOKEN',
    REMOVE_ACCESS_TOKEN: 'USERS.REMOVE_ACCESS_TOKEN',
    FORGOT_PASSWORD: 'USERS.FORGOT_PASSWORD'
};

export const ACTIVITIES = {
    SET_ACTIVE_TAB: 'ACTIVITIES.SET_ACTIVE_TAB',
    GET_MORE_TXN: 'ACTIVITIES.GET_MORE_TXN',
    GET_MORE_TXN_SUCCESS: 'ACTIVITIES.GET_MORE_TXN_SUCCESS',
    GET_MORE_TXN_FAILED: 'ACTIVITIES.GET_MORE_TXN_FAILED',
    GET_TXN_DETAIL: 'ACTIVITIES.GET_TXN_DETAIL',
    GET_TXN_DETAIL_SUCCESS: 'ACTIVITIES.GET_TXN_DETAIL_SUCCESS',
    GET_TXN_DETAIL_FAILED: 'ACTIVITIES.GET_TXN_DETAIL_FAILED',
};

export const TABS = {
    SET_ACTIVE: 'TABS.SET_ACTIVE'
};