export const COMMONS = {
    TOGGLE_LOADING: 'COMMONS.TOGGLE_LOADING',
    SHOW_ERROR: 'COMMONS.SHOW_ERROR'
};

export const USERS = {
    LOGIN: 'USERS.LOGIN',
    LOGIN_SUCCESS: 'USERS.LOGIN_SUCCESS',
    LOGIN_FAILED: 'USERS.LOGIN_FAILED',
    LOGOUT: 'USERS.LOGOUT',
    SSO_LOGIN_SUCCESS: 'USERS.SSO_LOGIN_SUCCESS',
    SSO_LOGIN_FAILED: 'USERS.SSO_LOGIN_FAILED',
    GET_PROFILE_SUCCESS: 'USERS.GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED: 'USERS.GET_PROFILE_FAILED',
    GET_MY_WALLETS_SUCCESS: 'USERS.GET_MY_WALLETS_SUCCESS',
    GET_MY_WALLETS_FAILED: 'USERS.GET_MY_WALLETS_FAILED',
    REMEMBER_ME: 'USERS.REMEMBER_ME',
    SAVE_ACCESS_TOKEN: 'USERS.SAVE_ACCESS_TOKEN',
    REMOVE_ACCESS_TOKEN: 'USERS.REMOVE_ACCESS_TOKEN',
    FORGOT_PASSWORD: 'USERS.FORGOT_PASSWORD'
};

export const ACTIVITIES = {
    SET_ACTIVE_TAB: 'ACTIVITIES.SET_ACTIVE_TAB',
    GET_MORE_TXN: 'ACTIVITIES.GET_MORE_TXN',
    GET_MORE_TXN_SUCCESS: 'ACTIVITIES.GET_MORE_TXN_SUCCESS',
    GET_MORE_TXN_FAILED: 'ACTIVITIES.GET_MORE_TXN_FAILED',
    GET_TXN_DETAIL: 'ACTIVITIES.GET_TXN_DETAIL',
    GET_TXN_DETAIL_SUCCESS: 'ACTIVITIES.GET_TXN_DETAIL_SUCCESS',
    GET_TXN_DETAIL_FAILED: 'ACTIVITIES.GET_TXN_DETAIL_FAILED',
};

export const SEND = {
    CREATE_RAW_TXN: 'SEND.CREATE_RAW_TXN',
    CLEAR_FORM: 'SEND.CLEAR_FORM',
    SEND_TXN_SUCCESSFUL: 'SEND.SEND_TXN_SUCCESSFUL'
}

export const REQUEST = {
    REQUEST_MONEY: 'REQUEST.REQUEST_MONEY',
    REQUEST_MONEY_SUCCESS: 'REQUEST.REQUEST_MONEY_SUCCESS',
    REQUEST_MONEY_FAILED: 'REQUEST.REQUEST_MONEY_FAILED',
}

export const TABS = {
    SET_ACTIVE: 'TABS.SET_ACTIVE'
};